In [125]:
import numpy as np
import pandas as pd

In [126]:
df = pd.read_csv(r"C:\Users\123\Desktop\cars.csv")

In [127]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [128]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [129]:
x = df.drop(columns='selling_price')
y = df['selling_price']

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [132]:
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [133]:
y

0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8123    320000
8124    135000
8125    382000
8126    290000
8127    290000
Name: selling_price, Length: 8128, dtype: int64

3.OneHotEncoding

In [134]:
from sklearn.preprocessing import OneHotEncoder

In [135]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [136]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [137]:
x_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]], dtype=int32)

In [138]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [139]:
x_train_new.shape

(6502, 7)

In [140]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Toyota', 68089, 0, ..., 0, 0, 0],
       ['Chevrolet', 67600, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 1, ..., 0, 0, 0],
       ...,
       ['Mahindra', 60000, 1, ..., 0, 0, 0],
       ['Renault', 75000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 1, ..., 1, 0, 0]], dtype=object)

Most Frequent Categories

In [141]:
counts = df['brand'].value_counts()

In [142]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [143]:
df['brand'].nunique()
treshold = 100

In [144]:
repl = counts[counts >= treshold].index

In [145]:
repl

Index(['Maruti', 'Hyundai', 'Mahindra', 'Tata', 'Toyota', 'Honda', 'Ford',
       'Chevrolet', 'Renault', 'Volkswagen', 'BMW', 'Skoda'],
      dtype='object', name='brand')

In [146]:
df = df[df['brand'].isin(repl)]

In [147]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [148]:
df['brand'].value_counts()

brand
Maruti        2448
Hyundai       1415
Mahindra       772
Tata           734
Toyota         488
Honda          467
Ford           397
Chevrolet      230
Renault        228
Volkswagen     186
BMW            120
Skoda          105
Name: count, dtype: int64